name = "Client Enhancements"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35c8d7fd88e6a55fafef975eea85336482c2abdfda53459fc91af3ff91c498b7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.3-beta.1"
