name = "Client Enhancements"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d25c62af799a64ee2a81dca52eafdc13997beb7671aeaf678cc2e6b37b01d2fb"

[versions]
minecraft = "1.20.1"
quilt = "0.19.3-beta.1"
